[Interface]
Address = 10.226.0.12
PrivateKey = uB84nBQI7d7R2h8kyGXSXTXyKTZ7rzL/NYhn+BX/kUE=
MTU = 1350

[Peer]
PublicKey = wOWU2tj1zY4hUFSZucKaLh4bbF3vX9Pw/Qj/gDjU1D0=
Endpoint = vpn.clientes.adaptive.com.br:51820
AllowedIPs = 10.226.0.1
PersistentKeepalive = 25