[Interface]
Address = 10.226.0.12
PrivateKey = QKqzDFCQmHjluIMCe20R68+MFmlFcEicL4stLuaoj0g=
MTU = 1350

[Peer]
PublicKey = OKClG8AjsqMLMwDR/x8Ys+Ol9OWsAiPegUKBHXDzn0k= 
Endpoint = 35.247.210.213:51820
AllowedIPs = 10.226.0.1
PersistentKeepalive = 25


